//! GTK4/libadwaita UI layer — window, sidebar, panels, dialogs, and settings.

pub mod all_surfaces_search;
pub mod file_explorer;
#[cfg(feature = "webkit")]
pub mod browser_panel;
pub mod command_palette;
pub mod diff_panel;
pub mod dock;
pub mod dock_editor;
pub mod file_preview_panel;
pub mod history_panel;
#[cfg(feature = "webkit")]
pub mod markdown_panel;
pub mod notes_panel;
pub mod vault_panel;
pub mod notifications_panel;
pub mod omnibar;
pub mod pane_overview;
pub mod project_panel;
pub mod quick_terminal;
pub mod search_overlay;
pub mod settings;
pub mod sidebar;
pub mod split_view;
pub mod state_sprite;
pub mod task_manager;
pub mod terminal_panel;
pub mod textbox;
pub mod welcome;
pub mod window;
